spring:
  data:
    mongodb:
      uri: mongodb+srv://username:password@cluster0.un0kaso.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: InterviewPrep
      auto-index-creation: true
  ai:
    openai:
      api-key: {{API-KEY}}
      base-url: https://api.groq.com/openai

